version: "3"
services:
  app:
    container_name: purchapi
    build: .
    environment:
      - DATABASE_HOST: purchdb
    ports:
      - "9001:80"
    volumes:
      - ../www:/var/www
    depends_on:
      - db
  db:
    container_name: purchdb
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: purchmsg
      MARIADB_USER: purch
      MARIADB_PASSWROD: purch
    volumes:
      - ../db:/var/lib/mysql
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
