version: "3"
services:
  app:
    container_name: purchapi
    build: .
    restart: unless-stopped
    environment:
      DATABASE_HOST: purchdb
    ports:
      - 9001:80
    volumes:
      - ../www:/var/www
 #   depends_on:
 #     - db
  db:
    container_name: purchdb
    image: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_HOST: '%'
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: purch
      MARIADB_PASSWORD: purch
      MARIADB_DATABASE: purchmsg
    volumes:
      - ../db:/var/lib/mysql
      - ../sql:/sql
#    command: 'mysql -h 127.0.0.1 -e "source /sql/purch.sql;" -u$MARIADB_DATABASE -p$MRIADB_PASSWORD'
  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
