GRANT ALL PRIVILEGES ON *.* TO 'purch'@'%' IDENTIFIED BY 'purch' WITH GRANT OPTION; 

CREATE TABLE IF NOT EXISTS `PURCH_MSG` (
	`PURCH_ID` INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,

	`NAME` VARCHAR(200) CHARACTER SET utf8 NOT NULL,
	`MESSAGE` VARCHAR(400) CHARACTER SET utf8 NOT NULL,
	`RESPONSE` VARCHAR(400) CHARACTER SET utf8,
  `PURCHASE_COUNT` INT(5) zerofill,
	`PURCHASE_SUMMARY` VARCHAR(400) CHARACTER SET utf8 NOT NULL, -- list of item names & purcheas counts

	`PURCHASE_IMAGE_URL` VARCHAR(200) CHARACTER SET utf8 NOT NULL,

	`CREATED_STAMP` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`RESPONSE_STAMP` DATETIME NULL,   -- when response was sumbitted
	`ONSCREEN_STAMP` DATETIME NULL,   -- when response was sumbitted

	`CURATED_STAMP` DATETIME NULL,   -- To show up in Curated filter list     unless RESPONSE_STAMP OR CURATED_COMPLETE_STAMP
	`CURATED_COMPLETE_STAMP` DATETIME NULL,   -- Prevents from showing up in curated 

	INDEX `idx_pcount` (`PURCHASE_COUNT`),
	INDEX `idx_rstamp` (`RESPONSE_STAMP`),
	INDEX `idx_ostamp` (`ONSCREEN_STAMP`),
	INDEX `idx_cstamp` (`CURATED_STAMP`),
	INDEX `idx_ccstamp` (`CURATED_COMPLETE_STAMP`)

) ENGINE=MyISAM;


CREATE TABLE IF NOT EXISTS `PURCH_ACTIVE` (
	`PURCH_ACTIVE_ID` INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`ACTIVE` INT(5) NOT NULL,
	`ACTIVE_STAMP` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	INDEX `idx_active` (`ACTIVE`),
	INDEX `idx_stamp`  (`ACTIVE_STAMP`)
) ENGINE=MyISAM;