GRANT ALL PRIVILEGES ON *.* TO 'purch'@'%' IDENTIFIED BY 'purch' WITH GRANT OPTION; 

CREATE TABLE IF NOT EXISTS `PURCH_MSG` (
	`PURCH_ID` INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,

	`NAME` VARCHAR(200) CHARACTER SET utf8 NOT NULL,
	`MESSAGE` VARCHAR(400) CHARACTER SET utf8 NOT NULL,
	`RESPONSE` VARCHAR(400) CHARACTER SET utf8,
	`PURCHASE_COUNT` INT(5) zerofill,
	`PURCHASE_SUMMARY` VARCHAR(400) CHARACTER SET utf8 NOT NULL, -- list of item names & purcheas counts

	`PURCHASE_IMAGE_URL` VARCHAR(200) CHARACTER SET utf8 NOT NULL,

	`CREATED_STAMP` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`RESPONSE_STAMP` DATETIME NULL,   -- when response was sumbitted
	`ONSCREEN_STAMP` DATETIME NULL,   -- when response was sumbitted

	`CURATED_STAMP` DATETIME NULL,   -- To show up in Curated filter list     unless RESPONSE_STAMP OR CURATED_COMPLETE_STAMP
	`CURATED_COMPLETE_STAMP` DATETIME NULL,   -- Prevents from showing up in curated 


		INDEX `idx_pcount` (`PURCHASE_COUNT`)
) ENGINE=MyISAM;