GRANT ALL PRIVILEGES ON *.* TO 'purch'@'%' IDENTIFIED BY 'purch' WITH GRANT OPTION; 

CREATE TABLE IF NOT EXISTS `PURCH_MSG` (
	`PURCH_ID` INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,

	`NAME` VARCHAR(200) CHARACTER SET utf8 NOT NULL,
	`MESaSAGE` VARCHAR(400) CHARACTER SET utf8 NOT NULL,
	`RESPONSE` VARCHAR(400) CHARACTER SET utf8 NOT NULL,
	`PURCHASE_COUNT` INT(20) zerofill,
	`PURCHASE_SUMMARY` VARCHAR(400) CHARACTER SET utf8 NOT NULL, -- list of item names & purcheas counts

	`PURCHASE_IMAGE_URL` VARCHAR(200) CHARACTER SET utf8 NOT NULL,

	`CREATED_STAMP` DATETIME NOT NULL,
    `RESPONSE_STAMP` DATETIME NULL,   -- when response was sumbitted
    `ONSCREEN_STAMP` DATETIME NULL,   -- when response was sumbitted


	`CURATED_STAMP` DATETIME NULL,   -- To show up in Curated filter list     unless RESPONSE_STAMP OR CURATED_COMPLETE_STAMP
	`CURATED_COMPLETE_STAMP` DATETIME NULL,   -- Prevents from showing up in curated 

	--FULLTEXT `idx_msg` (`MESSAGE`) USING BTREE,
	--FULLTEXT `idx_psum` (`PURCHASE_SUMMARY`) USING BTREE,
    INDEX `idx_pcount` (`PURCHASE_COUNT`)
) ENGINE=MyISAM;